export * from "./schema.js";
export * from "./types.js";
export * from "./confidence.js";
export * from "./db.js";
export { setupFTS, searchFTS } from "./fts.js";
export { generateEmbedding, generateEmbeddings, getEmbedder, backfillEmbeddings, EMBEDDING_DIM } from "./embeddings.js";
export { setupVec, insertEmbedding, deleteEmbedding, searchVec } from "./vec.js";
export { hybridSearch } from "./search.js";
export type { SearchResult, ExpandedResult } from "./search.js";
export { contextSearch } from "./context-packing.js";
export type { ContextPackedResult, HierarchicalResult, NarrativeResult, ContextMemory, ContextSummary, ContextReference, EntityProfileSummary } from "./context-packing.js";
export { bumpLastModified } from "./db.js";
export { detectSensitiveData, redactSensitiveData } from "./pii.js";
export type { PiiMatch } from "./pii.js";
export { encrypt, decrypt, deriveKeys, generateSalt, encryptMemory, decryptMemory } from "./crypto.js";
export type { EncryptionKeys } from "./crypto.js";
export { loadCredentials, saveCredentials, initCredentials, loadConfig, saveConfig } from "./credentials.js";
export type { Credentials, LodisConfig } from "./credentials.js";
export { migrateToCloud, migrateToLocal, exportMemories, importFromExport } from "./migrate.js";
export type { LodisExportData } from "./migrate.js";
export { bulkInsertMemories } from "./bulk.js";
export type { BulkEntry, BulkInsertOptions, BulkInsertResult, BulkResultEntry, BulkStatus } from "./bulk.js";
export { getOrGenerateProfile, saveProfile, getProfile, isProfileStale, listProfiles } from "./entity-profiles.js";
export type { EntityProfile } from "./entity-profiles.js";
export { generateToken, hashToken } from "./tokens.js";
export { userSettings, apiTokens } from "./schema.js";
export type { Client } from "@libsql/client";
export { CHAPTERS, listChapters, getChapter, isKnownChapterId, chapterToMarkdown, tocToMarkdown } from "./tutorial/index.js";
export type { Chapter, ChapterId, Section, ToolReference, TryItNext, ChapterFormat } from "./tutorial/index.js";
